
DBHOSTNAME=#
MEMCACHEHOSTNAME=#
RABBITMQHOSTNAME=#
TOMCATHOSTNAME=#
NGINXHOSTNAME=#
export DBHOSTNAME
export MEMCACHEHOSTNAME
export RABBITHOSTNAME
export TOMCATHOSTNAME
export NGINXHOSTNAME


DBHOSTNAME=#
MEMCACHEHOSTNAME=#
RABBITMQHOSTNAME=#
TOMCATHOSTNAME=#
NGINXHOSTNAME=#
export DBHOSTNAME
export MEMCACHEHOSTNAME
export RABBITHOSTNAME
export TOMCATHOSTNAME
export NGINXHOSTNAME

