#usr/bin/bash

DB_HOSTNAME=$1
MEMCACHE_HOSTANME=$2
RABBITMQ_HOSTNAME=$3
TOMCAT_HOSTNAME=$4
NGINX_HOSTNAME=$5

echo "
DBHOSTNAME=$DB_HOSTNAME
MEMCACHEHOSTNAME=$MEMCACHE_HOSTNAME
RABBITMQHOSTNAME=$RABBITMQ_HOSTNAME
TOMCATHOSTNAME=$TOMCAT_HOSTNAME
NGINXHOSTNAME=$NGINX_HOSTNAME
export DBHOSTNAME
export MEMCACHEHOSTNAME
export RABBITHOSTNAME
export TOMCATHOSTNAME
export NGINXHOSTNAME
" >> /home/vagrant/.bashrc 


